version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: your_password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
